<a href="https://colab.research.google.com/github/Ashwini0187/AshwiniChoudhary/blob/main/statistic_and_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import statistics as st
data = [45,87,69,15,21,32,15,10,25,26,27,89,30,100]

print("Arithmetic Mean " , st.mean(data))


print("Geometric Mean " , st.geometric_mean(data))


print("Harmonic Mean " , st.harmonic_mean(data))

print("Median  " , st.median(data))

print("Mode  " , st.mode(data))



Arithmetic Mean  42.214285714285715
Geometric Mean  33.123575974392544
Harmonic Mean  26.391219072176252
Median   28.5
Mode   15


In [2]:
import statistics as st
# Measure of Dispersion:
      # How much data is dispersed or spread out

#DataSet
data = [1,2,3,4,5,6,7,8,9,10 , 12 , 15 , 16 , 19 , 87 , 27]



#Mean :
Mean = st.mean(data)
print("Mean :" ,Mean)



#Median

Median = st.median(data)
print("Median :" ,Median)



# Range = Max-Min
Range = (max(data)-min(data))
print("Range of the given list is :" ,Range )

#Standard Variation:
    # It is measure of how much our data values is deviating from mean value
sd=st.stdev(data)
print("standard deviation",sd)


#Variance :
#Square of Standard Deviation
Variance = st.variance(data)
print("variance", Variance)

#InterQuartile Range :
      # IQR : Q3-Q1
q = st.quantiles(data)
# IQR1 = q[3] - q[1] # this is not working



IQR = q[2] - q[0]

# print("InterQuartile Range: " , IQR1)
print("InterQuartile Range: " , IQR2)

Mean : 14.4375
Median : 8.5
Range of the given list is : 86
standard deviation 20.54902674094323
variance 422.2625
InterQuartile Range:  11.5


In [4]:
#program for z test

import statistics as st
from statsmodels.stats import weightstats as stests
from numpy import random

ages = random.randint(10, 50, size=(30))
print("data", ages)
ages_mean = st.mean(ages)
print("mean of data",ages_mean)
std_dev = st.stdev(ages)
print("Standard Deviation :" , std_dev)
ztest, pval = stests.ztest(ages, value=30)
print("Ztest Score :" ,ztest)
print("P value :" ,pval)
if(pval<0.05):
 print("Reject Null Hypothesis")
else:
 print("Accept the Null hypothesis")

data [18 19 38 18 24 41 35 13 32 35 42 28 39 32 43 20 41 30 41 14 26 13 20 17
 40 39 46 10 19 35]
mean of data 28
Standard Deviation : 10.954451150103322
Ztest Score : -0.5321216386750659
P value : 0.594641751343211
Accept the Null hypothesis


In [1]:
!pip install numpy

In [3]:
import numpy as np

In [4]:
#1-D Array
a= np.array([1,2,3,4,5])
print(a)

[1 2 3 4 5]


In [12]:
#2-D Arrays
b = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(b)
b[1][2]

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


8

In [64]:
c=np.zeros(10)
print(c)
print(type(c))

c.dtype
d = np.ones(10)
d
#print(d)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
<class 'numpy.ndarray'>


array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [25]:
np.empty(10)
#g = np.empty(2)
#print(g)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [27]:
np.arange(2,9)

array([2, 3, 4, 5, 6, 7, 8])

In [28]:
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [66]:
x=np.ones(5,dtype=np.int64)
x
x.dtype
#print(dtype(x))

NameError: name 'dtype' is not defined

In [35]:
y =  np.zeros(10  , dtype = np.int64)
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [37]:
arr = np.array([2,1,5,9,8,7,89,91,25,200])
print(arr)
np.sort(arr)

[  2   1   5   9   8   7  89  91  25 200]


array([  1,   2,   5,   7,   8,   9,  25,  89,  91, 200])

In [38]:
c = np.sort(arr)
c[::-1]

array([200,  91,  89,  25,   9,   8,   7,   5,   2,   1])

In [39]:
l = [54,87,98,95,65]
l.sort(reverse = True)
print(l)

[98, 95, 87, 65, 54]


In [43]:
a=np.array([1,2,3,4,5])
b=np.array([6,8,9,7,10,11])

np.concatenate((a, b),axis = 0)

array([ 1,  2,  3,  4,  5,  6,  8,  9,  7, 10, 11])

In [46]:
x = np.array([[1,2], [3,4]])
y = np.array([[5,6]])

np.concatenate((x,y))

array([[1, 2],
       [3, 4],
       [5, 6]])

In [52]:
g = np.array([
              [[1,2,3,4],
              [5,6,7,8]],

              [[1,2,3,4],
              [5,6,7,8]],

              [[1,2,3,4],
              [5,6,7,8]],

              ])
print(g)

[[[1 2 3 4]
  [5 6 7 8]]

 [[1 2 3 4]
  [5 6 7 8]]

 [[1 2 3 4]
  [5 6 7 8]]]


In [51]:
g.ndim

3

In [53]:
g.size

24

In [54]:
g.shape

(3, 2, 4)

In [55]:
a = np.arange(6)
print(a)

[0 1 2 3 4 5]


In [58]:
reshap = a.reshape(3,2)
print(reshap)

[[0 1]
 [2 3]
 [4 5]]


In [61]:
a.reshape(-1,1)

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

In [63]:
g.reshape(-1,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8]])